Semestre 1/2023-06-16 Projeto Gamer/Controllers/EquipeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using projeto_gamer_fullstack.Infra;
using projeto_gamer_fullstack.Models;

namespace projeto_gamer_fullstack.Controllers
{
    [Route("[controller]")]
    public class EquipeController : Controller
    {
        private readonly ILogger<EquipeController> _logger;

        public EquipeController(ILogger<EquipeController> logger)
        {
            _logger = logger;
        }

        Context c = new Context(); //* Instância Context que acessa o banco de dados

        [Route("Listar")]//*http:/localhost/Equipe/Listar
        public IActionResult Index()
        {
            ViewBag.UserName = HttpContext.Session.GetString("UserName");
            ViewBag.Equipe = c.Equipe.ToList(); //* "Mochila" que contém equipes. 
            return View(); //* Esta "mochila" pode ser usada no View de equipe.
        }


        [Route("Cadastrar")]
        public IActionResult Cadastrar(IFormCollection form)
        {
            Equipe novaEquipe = new Equipe();

            novaEquipe.Nome = form["Nome"].ToString();

            // vem como string, o que precisamos é imagem
            // novaEquipe.Imagem = form["Imagem"].ToString();
        Console.WriteLine($"Anexo : {form.Files.Count}");
            // lógica do upload de imagem
            if (form.Files.Count > 0)
            {
                var file = form.Files[0];
                // variavel criando combinações de caminhos
                var folder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/Equipe");

                if (!Directory.Exists(folder))
                {
                    Directory.CreateDirectory(folder);
                }

                var path = Path.Combine(folder, file.FileName);

                // using é o bloco de codigo onde após de terminar ele se encerra
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    file.CopyTo(stream);
                }

                novaEquipe.Imagem = file.FileName;

            }
            else
            {
                novaEquipe.Imagem = "default.png";
            }
            // fima da lógica de upload

            c.Equipe.Add(novaEquipe);
            // c.Add(novaEquipe) - Isso também funciona

            c.SaveChanges();

            return LocalRedirect("~/Equipe/Listar");
        }

        [Route("Excluir/{id}")]
        public IActionResult Excluir(int id)
        {
            Equipe e = c.Equipe.First(e => e.IdEquipe == id);

            c.Equipe.Remove(e);

            c.SaveChanges();

            return LocalRedirect("~/Equipe/Listar");
        }


        [Route("Editar/Id")]
        public IActionResult Editar(int id)
        {
            Equipe e = c.Equipe.First(e => e.IdEquipe == id);
            ViewBag.UserName = HttpContext.Session.GetString("UserName");
            ViewBag.Equipe = e;

            return View("Edit");
        }

        [Route("Atualizar")]
        public object Atualizar(IFormCollection form, Equipe e)
        {
            Equipe novaEquipe = new Equipe();
            Equipe equipe = c.Equipe.First(x => x.IdEquipe == e.IdEquipe);

            if (form.Files.Count > 0)
            {
                var file = form.Files[0];
                var folder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/Equipes");
                if (!Directory.Exists(folder))
                {
                    Directory.CreateDirectory(folder);
                }

                var path = Path.Combine(folder, file.FileName);

                using (var stream = new FileStream(path, FileMode.Create))
                {
                    file.CopyTo(stream);
                }
                novaEquipe.Imagem = file.FileName;
                equipe.Imagem = novaEquipe.Imagem;
            }

            novaEquipe.Nome = form["Nome"].ToString();

            if (!string.IsNullOrEmpty(novaEquipe.Nome))
            {
                equipe.Nome = novaEquipe.Nome;
            }

            c.Equipe.Update(equipe);
            c.SaveChanges();

            return LocalRedirect("~/Equipe/Listar");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Semestre 1/2023-06-16 Projeto Gamer/Controllers/JogadorController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using projeto_gamer_fullstack.Infra;
using projeto_gamer_fullstack.Models;

namespace projeto_gamer_fullstack.Controllers
{
    [Route("[controller]")]
    public class JogadorController : Controller
    {
        private readonly ILogger<JogadorController> _logger;

        public JogadorController(ILogger<JogadorController> logger)
        {
            _logger = logger;
        }

        Context c = new Context(); //* Instância Context que acessa o banco de dados

        [Route("Listar")]
        public IActionResult Index()
        {
            ViewBag.UserName = HttpContext.Session.GetString("UserName");
            ViewBag.Jogador = c.Jogador.ToList();
            ViewBag.Equipe = c.Equipe.ToList();
            return View();
        }

        [Route("Cadastrar")]
        public IActionResult Cadastrar(IFormCollection form)
        {
            Jogador novoJogador = new Jogador();

            novoJogador.IdEquipe = int.Parse(form["Equipe"]);
            novoJogador.Equipe = c.Equipe.First(x => x.IdEquipe == int.Parse(form["Equipe"]));
            novoJogador.Nome = form["JogadorNome"].ToString();
            novoJogador.Email = form["JogadorEmail"].ToString();
            novoJogador.Senha = form["JogadorSenha"].ToString();

            c.Jogador.Add(novoJogador);
            c.SaveChanges();

            return LocalRedirect("~/Jogador/Listar");
        }

        [Route("Excluir")]
        public IActionResult Excluir(int id)
        {
            Jogador j = c.Jogador.First(x => x.IdJogador == id);
            c.Jogador.Remove(j);
            c.SaveChanges();

            return LocalRedirect("~/Jogador/Listar");
        }

        [Route("Editar/Id")]
        public IActionResult Editar(int id)
        {
            Jogador jogadorSelecionado = c.Jogador.First(x => x.IdJogador == id);
            ViewBag.Jogador = jogadorSelecionado;
            ViewBag.Equipe = c.Equipe.ToList();
            return View("Edit");
        }

        [Route("Atualizar")]
        public IActionResult Atualizar(IFormCollection form)
        {
            Jogador novoJogador = new Jogador();
            novoJogador.IdJogador = int.Parse(form["IdJogador"].ToString());
            Jogador jogadorSelecionado = c.Jogador.First(x => x.IdJogador == novoJogador.IdJogador);

            if (!string.IsNullOrEmpty(form["JogadorNome"].ToString()))
            {
                novoJogador.Nome = form["JogadorNome"].ToString();
                jogadorSelecionado.Nome = novoJogador.Nome;
            }

            if (!string.IsNullOrEmpty(form["JogadorEmail"].ToString()))
            {
                novoJogador.Email = form["JogadorEmail"].ToString();
                jogadorSelecionado.Email = novoJogador.Email;
            }

            if (string.IsNullOrEmpty(form["JogadorSenha"].ToString()))
            {
                novoJogador.Senha = form["JogadorSenha"].ToString();
                jogadorSelecionado.Senha = novoJogador.Senha;
            }

            novoJogador.IdEquipe = int.Parse(form["Equipe"]);
            jogadorSelecionado.IdEquipe = novoJogador.IdEquipe;
            jogadorSelecionado.Equipe = c.Equipe.First(x => x.IdEquipe == jogadorSelecionado.IdEquipe);

            c.Jogador.Update(jogadorSelecionado);
            c.SaveChanges();

            return LocalRedirect("~/Jogador/Listar");
        }
    }
}

Semestre 1/2023-06-16 Projeto Gamer/Views/Shared/_Layout copy.cshtml
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">projeto_gamer_fullstack</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if(ViewBag.UserName != null){
                        <li class="nav-item nav-link text-dark"><strong>Usuário</strong> @ViewBag.UserName</li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Equipe" asp-action="Index">Equipes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Jogador" asp-action="Index">Jogadores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Logout" asp-action="Index">Logout</a>
                        </li>
                        }
                        else{
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                        </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - projeto_gamer_fullstack - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Semestre 1/2023-06-16 Projeto Gamer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Projeto Gamer </title>
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/header-footer.css">  
</head>
<body>
            <!-- HEADER -->
    <header class="header">
        <div class="header-top">
            <div class="container-grid header-top-flex">
                <div>
                    <span class="phone-box">
                        <img src="~/assets/phone-icon.png" alt="phone icon" title="Ícone Telefone">
                        (11) 0900-1010
                    </span>

                    <span class="mail-box">
                        <img src="~/assets/envelope-icon.png" alt="envelope icon" title="Ícone Envelope">
                        contato@gamer.com.br
                    </span>
                </div>

                <span class="social-box">
                    <a href="https://facebook.com/" target=”_blank”>
                    <img src="~/assets/facebook.svg" alt="phone icon" title="Ícone Telefone"></a>
                    <a href="https://www.linkedin.com/" target=”_blank”>
                    <img src="~/assets/linkedin.svg" alt="phone icon" title="Ícone Telefone"></a>
                    <a href="https://www.instagram.com/" target=”_blank”>
                    <img src="~/assets/instagram.svg" alt="phone icon" title="Ícone Telefone"></a>
                </span>
            </div>
        </div>
        <div class="header-bottom">
            <div class="container-grid header-bottom">
                <label for="mostra-esconde-navmenu"><img src="~/assets/menu-hamburger.svg" alt="Menu Hamburger"
                        title="Ícone Menu">
                </label>


                <h1>
                    <span class="title">Gamer</span>
                    <img src="~/assets/logotipo-gamer.svg" id="logotipo" alt="Logotipo Gamer" title="Gamer Logotipo">
                </h1>

                <input type="checkbox" id="mostra-esconde-navmenu">
                <div class="nav-bkg">
                    <nav>
                        <a asp-area="" asp-controller="Home" asp-action="Index">Início</a>
                        <a href="~/#noticias">Notícias</a>
                        @if(ViewBag.UserName != null){
                        <a asp-area="" asp-controller="Equipe" asp-action="Index">Equipes</a>
                        <a asp-area="" asp-controller="Jogador" asp-action="Index">Jogadores</a>
                        <a asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                        }
                        else{
                        <a asp-area="" asp-controller="Login" asp-action="Login">Login</a>
                        }

                        <a class="phone-box">
                            <img src="~/assets/phone-icon.png" alt="phone icon" title="Ícone Telefone">
                            (11) 0900-1010
                        </a>
                        <a class="mail-box">
                            <img src="~/assets/envelope-icon.png" alt="envelope icon" title="Ícone Envelope">
                            contato@gamer.com.br
                        </a>

                        <!-- social icons -->
                        <span class="social-box">
                            <a href="https://facebook.com/" target=”_blank”>
                            <img src="~/assets/facebook.svg" alt="phone icon" title="Ícone Telefone"></a>
                            <a href="https://www.linkedin.com/" target=”_blank”>
                            <img src="~/assets/linkedin.svg" alt="phone icon" title="Ícone Telefone"></a>
                            <a href="https://www.instagram.com/" target=”_blank”>
                            <img src="~/assets/instagram.svg" alt="phone icon" title="Ícone Telefone"></a>
                        </span>
                    </nav>
                </div>
                <!-- Header Menu Ícones laterais -->
                <label for="mostra-esconde-icones">
                    <img src="~/assets/menu-points.png" alt="Menu Points">
                </label>

                <input type="checkbox" id="mostra-esconde-icones">
                <div class="icons-header-bkg">
                    <div class="icons-header">
                        @if(ViewBag.UserName != null){
                        <a asp-area="" asp-controller="Login" asp-action="Logout">
                        <img src="~/assets/user-icon.svg" alt="user-login"> </a>
                        <img src="~/assets/market-icon.png" alt="market icon">
                        <img src="~/assets/search-icon.png" alt="search icon">}
                    </div>
                </div>
            </div>
        </div>
    </header>

        @RenderBody()

        @** FOOTER *@
    <footer>
        <div class="container-grid footer-flex">

            <div class="card-ftitem-box">
                <a href="#" id="ftlogo-link">
                    <img src="~/assets/logotipo-gamer.svg" id="ftlogo" alt="Home">
                </a>
                <p>Nosso sucesso na criação de soluções de negócios se deve em grande parte à nossa equipe talentosa e
                    altamente comprometida.</p>
                <div class="social-fticons">
                    <a href="https://facebook.com/" target=”_blank”>
                        <img src="~/assets/facebook-yellow.svg" alt="Icone Facebook">
                    </a>
                    <a href="https://www.linkedin.com/" target=”_blank”>
                        <img src="~/assets/linkedin-yellow.svg" alt="Icone Linkedin">
                    </a>
                    <a href="https://www.instagram.com/" target=”_blank”>
                        <img src="~/assets/instagram-yellow.svg" alt="Icone instagram">
                    </a>
                </div>
            </div>


            <div class="card-ftitem-box">
                <div>
                    <h2>Links Úteis</h2>
                    <hr>
                </div>

                <ul class="menu-footer">
                    <li class="menu-ftitem"><a href="#">Início</a></li>
                    <li class="menu-ftitem"><a href="~/#noticias">Notícias</a></li>
                    @if(ViewBag.UserName != null){
                    <li class="menu-ftitem"><a asp-area="" asp-controller="Equipe" asp-action="Index">Equipes</a></li>
                    <li class="menu-ftitem"><a asp-area="" asp-controller="Jogador" asp-action="Index">Jogadores</a></li>
                    <li class="menu-ftitem"><a asp-area="" asp-controller="Login" asp-action="Logout">Logout</a></li>
                    }
                    else{
                        <li class="menu-ftitem"><a asp-area="" asp-controller="Login" asp-action="Login">Login</a></li>
                    }
                </ul>
            </div>

            <div class="card-ftitem-box">
                <div>
                    <h2>Contatos</h2>
                    <hr>
                </div>

                <div>
                    <p class="contact-title">Localização:</p>
                    <p class="contact-text">Rua Niterói, 180 - São Caetano do Sul - SP</p>

                    <p class="contact-title">Junte-se a nós:</p>
                    <p class="contact-text"><a href="mailto:contato">contato@gamer.com.br</a></p>

                    <p class="contact-title">Telefone:</p>
                    <p class="contact-text">(11) 0900-1010</p>
                </div>
            </div>

            <div class="card-ftitem-box">
                <div>
                    <h2>Newsletter</h2>
                    <hr>
                </div>

                <form action="" class="frm-news">
                    <div class="input-box">
                        <input type="text" class="frm-input" placeholder="Digite seu email:">
                    </div>
                    <button type="button" class="frm-button">Enviar</button>
                </form>
            </div>

        </div>

        <div id="copyright">
            &#169;Copyright2022-GamerJogosDigitais
        </div>

        <img src="~/assets/Botao_voltar_ao_topo.svg" id="back-to-top" alt="Voltar ao Topo">
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>